[project]
name = "fdi_pln_26XX_p1"
version = "1.0"
description = "Agente de negociación autónoma para la Práctica 1 de PLN"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dynaconf",
    "pydantic",
    "pydantic-ai",
    "click",
    "rich",
    "fastapi>=0.133.0",
    "httpx>=0.28.1",
    "uvicorn>=0.41.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/fdi_pln_26XX_p1"]

[project.scripts]
fdi-pln-26XX-p1 = "fdi_pln_26XX_p1.main:cli"
